dict = {
    "Af/Asf": "as fuck",
    "Asl": "as hell",
    "Ate": "Girl, youatethatoutfit",
    "Aura": "Oh, you failed to rizz that level 10 gyatt? -1000000aura losslil bro",
    "Banger": "Play that song again, it's abanger",
    "Based": "to be yourself and not care about how others view you",
    "Basic": "basic bitch",
    "BDE": "big dick energy",
    "Bestie": "best friend",
    "Bet": "it's on",
    "Bffr": "Be fucking for real",
    "Big yikes": "Wow, when he failed that stunt, that was abig yikes",
    "Blud": "friend",
    "Boujee": "You must live in a castle since you're actingboujee",
    "Brainrot": "fanum tax",
    "Bruh": "brother",
    "Bussin'": "This salad isbussin",
    "Bussy": "Boy",
    "Cap": "capping",
    "Caught in 4K": "caught red-handed",
    "Cook": "cook",
    "Cooked (a": "Cooked",
    "Clapback": "Clap Back",
    "Dab": "cringe",
    "Dank": "I likedankmemes",
    "Ded": "kill you",
    "Delulu": "delusional",
    "Drip": "cool",
    "Era": "In My Era",
    "Extra": "They are soextra",
    "Fanum tax": "I need to pay myFanum tax, otherwise Fanum will lock me up in Ohio",
    "Fire": "#fire",
    "Fit/Fit check": "outfit",
    "Flex": "Not toflex, but I got a 98 on the test",
    "Gagged": "gagged",
    "Girlboss": "She's such agirlboss!",
    "Ghost": "Why do you keepghostingme?",
    "Glaze": "kiss-ass",
    "Glow-up": "glow-down",
    "GOAT": "You're theGOAT",
    "Gucci": "Those shoes aregucci",
    "Gyatt": "God Damn",
    "Glizzy": "glizzy",
    "Hits different": "hits different",
    "Ick": "Once in a Lifetime",
    "IJBOL": "I just burst out laughing",
    "I oop": "hit herballs",
    "iPad kid": "I need everyone else in my generation to promise that we are not going to raise 'iPad children.' ... You've been shoving media and screens in these kids' faces since birth",
    "It's giving": "It's givingyuck",
    "Iykyk": "If you know, you know",
    "Jit": "Sit down,jit",
    "Karen": "tattle on Black kids' lemonade stands",
    "Lit": "Enlightened",
    "Looksmaxxing": "We should startlooksmaxxing!",
    "Main character": "main character",
    "Mew": "Sorry, can't talk! I'm trying to learn how tomew",
    "Mid": "That movie was somid",
    "Moot/Moots": "mutuals",
    "Netflix and chill": "sexual",
    "NPC": "He's such anNPC. He has no personality",
    "OK Boomer": "Baby Boomer",
    "Oomf": "OOMFliked that post",
    "Oof": "oof",
    "Opp": "other peoples' pussy",
    "Out of pocket": "out of pocket",
    "Owned": "Get owned noob!",
    "Periodt": "full stop",
    "Pick-me": "She’s acting like such apick-me",
    "Pluh": "Soo...uhhh, yeah",
    "Pookie": "Hello, mypookie!",
    "Queen": "queen",
    "Ratio": "ratio",
    "Ratio": "I'm gonnaratioyou!",
    "Red flag": "How did I not notice all thered flags?",
    "Rizz": "He has all therizz, he gets every girl",
    "Roman Empire": "The ending ofHarry Potteris myRoman Empire",
    "Salty": "racy",
    "Secure the bag": "fumble the bag",
    "Sheesh": "sheeesh",
    "Shook": "I amshookafter that",
    "Sigma": "He is sosigma",
    "Simp": "soft",
    "Situationship": "I don't really know if he likes me or not, so for now it's asituationship",
    "Sksksk": "Wkwkwk",
    "Skibidi": "Skibidi",
    "Slaps": "excellence",
    "Slay": "flawless",
    "Sleep on": "sleep on it",
    "Snatched": "Your eyebrows aresnatchedaf",
    "Stan": "stalker",
    "Sus": "You're acting prettysus",
    "Tea": "hidden truth",
    "Touch grass": "go outside",
    "Tweaking": "high on meth",
    "Understood the assignment": "The Assignment",
    "UwU": "UwU, soft kisses",
    "Valid": "I agree, your opinion isvalidas hell",
    "Vibe check": "You need avibe check",
    "VSCO girl": "basic",
    "Wig": "make one'swigfly off",
    "Yap": "So I just need a petroleum tank, and lighter fluid to construct...",
    "Yeet" : "Heyeetedthat pencil across the classroom!",
    "Zesty" : "He's actingzesty"
}