dict = {
    "Af/Asf": "as fuck",
    "Asl": "as hell",
    "Ate": "slayed",
    "Aura": "vibe",
    "Banger": "great song",
    "Based": "authentic",
    "Basic": "unoriginal",
    "BDE": "big dick energy",
    "Bestie": "best friend",
    "Bet": "deal",
    "Bffr": "for real",
    "Big yikes": "cringe",
    "Blud": "friend",
    "Boujee": "luxurious",
    "Brainrot": "mind-numbing",
    "Bruh": "bro",
    "Bussin'": "delicious",
    "Bussy": "boy hole",
    "Cap": "lie",
    "Caught in 4K": "caught red-handed",
    "Cook": "excel",
    "Cooked": "destroyed",
    "Clapback": "retort",
    "Dab": "cringe",
    "Dank": "cool",
    "Ded": "dead",
    "Delulu": "delusional",
    "Drip": "style",
    "Era": "period",
    "Extra": "over the top",
    "Fanum tax": "price of fandom",
    "Fire": "awesome",
    "Fit/Fit check": "outfit",
    "Flex": "show off",
    "Gagged": "shocked",
    "Girlboss": "empowered woman",
    "Ghost": "ignore",
    "Glaze": "flatter",
    "Glow-up": "transformation",
    "GOAT": "greatest of all time",
    "Gucci": "stylish",
    "Gyatt": "impressive",
    "Glizzy": "hot dog",
    "Hits different": "feels unique",
    "Ick": "disgust",
    "IJBOL": "burst out laughing",
    "I oop": "unexpected",
    "iPad kid": "screen-obsessed",
    "It's giving": "it's like",
    "Iykyk": "if you know, you know",
    "Jit": "kid",
    "Karen": "entitled person",
    "Lit": "exciting",
    "Looksmaxxing": "enhancing appearance",
    "Main character": "center of attention",
    "Mew": "learn",
    "Mid": "average",
    "Moot/Moots": "mutuals",
    "Netflix and chill": "casual hangout",
    "NPC": "non-player character",
    "OK Boomer": "dismissive term",
    "Oomf": "one of my followers",
    "Oof": "painful",
    "Opp": "enemy",
    "Out of pocket": "inappropriate",
    "Owned": "defeated",
    "Periodt": "end of statement",
    "Pick-me": "attention-seeking",
    "Pluh": "hesitation",
    "Pookie": "sweetie",
    "Queen": "sovereign",
    "Ratio": "engagement",
    "Red flag": "warning sign",
    "Rizz": "charisma",
    "Roman Empire": "obsession",
    "Salty": "bitter",
    "Secure the bag": "achieve success",
    "Sheesh": "expression of awe",
    "Shook": "shocked",
    "Sigma": "independent",
    "Simp": "excessively attentive",
    "Situationship": "undefined relationship",
    "Sksksk": "laugh",
    "Skibidi": "dance",
    "Slaps": "excellent",
    "Slay": "flawless",
    "Sleep on": "underestimate",
    "Snatched": "perfect",
    "Stan": "obsessed fan",
    "Sus": "suspicious",
    "Tea": "gossip",
    "Touch grass": "go outside",
    "Tweaking": "acting strange",
    "Understood the assignment": "nailed it",
    "UwU": "cute",
    "Valid": "legitimate",
    "Vibe check": "mood check",
    "VSCO girl": "basic",
    "Wig": "exciting",
    "Yap": "talk",
    "Yeet": "throw",
    "Zesty": "enthusiastic"
}
